/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backend;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testAppShouldGreetWithHelloWorld() {
        App classUnderTest = new App();
        assertEquals("Hello world.", classUnderTest.getGreeting());
        assertNotEquals("Bye world.", classUnderTest.getGreeting());
    }
}
