matrix:
  include:
    - dist: xenial
      language: java
      jdk: oraclejdk11
      before_install:
        - cd projects/backend
      script:
        - ./gradlew test
        - ./gradlew check
        - ./gradlew build

    - language: node_js
      node_js: 10
      cache:
        directories:
        - projects/frontend/node_modules
      before_install:
        - cd projects/frontend
      install:
        - yarn
      script:
        - yarn test
        - yarn build
