E RuntimeError: data.slug must not be empty
/Users/adam/tmp/travis-build/lib/travis/build/data.rb:154:in `slug'
/Users/adam/tmp/travis-build/lib/travis/build/appliances/wait_for_network.rb:20:in `block in check_urls'
/Users/adam/tmp/travis-build/lib/travis/build/appliances/wait_for_network.rb:16:in `map'
/Users/adam/tmp/travis-build/lib/travis/build/appliances/wait_for_network.rb:16:in `check_urls'
/Users/adam/tmp/travis-build/lib/travis/build/appliances/wait_for_network.rb:10:in `apply'
/Users/adam/tmp/travis-build/lib/travis/build/appliances.rb:58:in `apply'
/Users/adam/tmp/travis-build/lib/travis/build/script.rb:294:in `configure'
/Users/adam/tmp/travis-build/lib/travis/build/stages/builtin.rb:12:in `block in run'
/Users/adam/tmp/travis-build/lib/travis/shell/builder.rb:186:in `with_options'
/Users/adam/tmp/travis-build/lib/travis/build/stages/base.rb:15:in `with_stage'
/Users/adam/tmp/travis-build/lib/travis/build/stages/builtin.rb:8:in `run'
/Users/adam/tmp/travis-build/lib/travis/build/stages.rb:126:in `block in run_stage'
/Users/adam/tmp/travis-build/lib/travis/shell/builder.rb:137:in `trace'
/Users/adam/tmp/travis-build/lib/travis/build/stages.rb:125:in `run_stage'
/Users/adam/tmp/travis-build/lib/travis/build/stages.rb:115:in `define_stage'
/Users/adam/tmp/travis-build/lib/travis/build/stages.rb:82:in `block in run'
/Users/adam/tmp/travis-build/lib/travis/build/stages.rb:81:in `each'
/Users/adam/tmp/travis-build/lib/travis/build/stages.rb:81:in `run'
/Users/adam/tmp/travis-build/lib/travis/build/script.rb:241:in `run'
/Users/adam/tmp/travis-build/lib/travis/build/script.rb:147:in `sexp'
/Users/adam/tmp/travis-build/lib/travis/build/script.rb:126:in `compile'
/Users/adam/.travis/travis-build/init.rb:51:in `run'
/Users/adam/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/cli/command.rb:198:in `execute'
/Users/adam/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/cli.rb:64:in `run'
/Users/adam/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/travis-1.8.9/bin/travis:18:in `<top (required)>'
/Users/adam/.travis/travis-build/bin/travis:29:in `load'
/Users/adam/.travis/travis-build/bin/travis:29:in `<main>'
E /Users/adam/tmp/travis-build/lib/travis/build/data.rb:154:in `slug'
/Users/adam/tmp/travis-build/lib/travis/build/appliances/wait_for_network.rb:20:in `block in check_urls'
/Users/adam/tmp/travis-build/lib/travis/build/appliances/wait_for_network.rb:16:in `map'
/Users/adam/tmp/travis-build/lib/travis/build/appliances/wait_for_network.rb:16:in `check_urls'
/Users/adam/tmp/travis-build/lib/travis/build/appliances/wait_for_network.rb:10:in `apply'
/Users/adam/tmp/travis-build/lib/travis/build/appliances.rb:58:in `apply'
/Users/adam/tmp/travis-build/lib/travis/build/script.rb:294:in `configure'
/Users/adam/tmp/travis-build/lib/travis/build/stages/builtin.rb:12:in `block in run'
/Users/adam/tmp/travis-build/lib/travis/shell/builder.rb:186:in `with_options'
/Users/adam/tmp/travis-build/lib/travis/build/stages/base.rb:15:in `with_stage'
/Users/adam/tmp/travis-build/lib/travis/build/stages/builtin.rb:8:in `run'
/Users/adam/tmp/travis-build/lib/travis/build/stages.rb:126:in `block in run_stage'
/Users/adam/tmp/travis-build/lib/travis/shell/builder.rb:137:in `trace'
/Users/adam/tmp/travis-build/lib/travis/build/stages.rb:125:in `run_stage'
/Users/adam/tmp/travis-build/lib/travis/build/stages.rb:115:in `define_stage'
/Users/adam/tmp/travis-build/lib/travis/build/stages.rb:82:in `block in run'
/Users/adam/tmp/travis-build/lib/travis/build/stages.rb:81:in `each'
/Users/adam/tmp/travis-build/lib/travis/build/stages.rb:81:in `run'
/Users/adam/tmp/travis-build/lib/travis/build/script.rb:241:in `run'
/Users/adam/tmp/travis-build/lib/travis/build/script.rb:147:in `sexp'
/Users/adam/tmp/travis-build/lib/travis/build/script.rb:126:in `compile'
/Users/adam/.travis/travis-build/init.rb:51:in `run'
/Users/adam/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/cli/command.rb:198:in `execute'
/Users/adam/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/cli.rb:64:in `run'
/Users/adam/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/travis-1.8.9/bin/travis:18:in `<top (required)>'
/Users/adam/.travis/travis-build/bin/travis:29:in `load'
/Users/adam/.travis/travis-build/bin/travis:29:in `<main>'
echo -e "[31;1m[0m"
echo -e "[31;1mThere was an error in the .travis.yml file from which we could not recover.
[0m"
echo -e "[31;1mUnfortunately, we do not know much about this error.[0m"
echo -e "[31;1m[0m"
echo -e "[31;1mPlease review https://docs.travis-ci.com[0m"
exit 2
